config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  get 'home/index'
  root to: 'home#index'
  
  resources :users, only: [:index, :show] do
    member do
      patch :resend_invite
    end
    
  end
  
  resources :tenants do
    get :my, on: :collection
  end
  
  resources :members do
    get :invite, on: :collection
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :tenant
  
  validates :tenant_id, presence: true
  validates_uniqueness_of :user_id, scope: :tenant
  
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :members
  has_many :users, through: :members
  
  
  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :invitable
         
  has_many :members
  has_many :tenants, through: :members
         
  def to_s
    email
  end
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include MembersHelper
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  def invite
    current_tenant = Tenant.first
    email = params[:email]
    user_from_email= User.where(email: email).first
    if user_in_db?(email)
      if Member.where(user: user_from_email, tenant: current_tenant).present?
        redirect_to members_path, alert: "The Organization #{current_tenant} already has a member #{email}"
        return
      else
        Member.create!(user: user_from_email, tenant: current_tenant)
        redirect_to members_path, notice: "User #{email} was added to #{current_tenant} from #{current_user}"
      end
    
     return
    else
      user_to_invite = User.invite!({ email: email }, current_user)
      Member.create!(user: user_to_invite, tenant: current_tenant)
      redirect_to members_path, notice: "User #{email} was invited to #{current_tenant} from #{current_user}"
    end
    
  end
  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:user_id, :tenant_id)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]

  # GET /tenants or /tenants.json
  def index
    @tenants = Tenant.all
  end

  def my
    @tenants = current_user.tenants
    render :index
  end
  # GET /tenants/1 or /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        @member = Member.create!(tenant: @tenant, user: current_user)
        format.html { redirect_to @tenant, notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def resend_invite
    user = User.find(params[:id])
    user.invite!
    redirect_to users_path, notice: "Invitation for #{user} has been re sent"
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(level)
    case level
        when 'notice' then "alert alert-info"
        when 'success' then "alert alert-success"
        when 'error' then "alert alert-danger"
        when 'alert' then "alert alert-danger"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
  
  def user_in_db?(email)
    User.where(email: email).first.present?
  end
  
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, message| %>
      <div class="<%= flash_class(msg_type)   %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2">
  <a class="navbar-brand" href="/">
    Navbar
  </a>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="container-fluid d-block d-md-flex justify-content-between">
            
      <% if current_user %>
        
          <ul class="navbar-nav mr-auto">
            <li class="<%= 'active fw-bold' if current_page?(root_path) %> nav-item">
              <%= link_to root_path, class: 'nav-link' do %>
                <div class="fa fa-home <%= 'text-white' if current_page?(root_path) %>"></div>
               <span class="<%= 'text-white' if current_page?(root_path) %>">
              Home</span>
              <% end %>
            </li>

            <li class="<%= 'active fw-bold' if current_page?(users_path) %> nav-item">
          <%= link_to users_path, class: 'nav-link' do %>
            <div class="fa fa-users <%= 'text-white' if current_page?(users_path) %>"></div>
            <span class="<%= 'text-white' if current_page?(users_path) %>">
              Users</span>
          <% end %>
        </li>
        
             <li class="<%= 'active fw-bold' if current_page?(tenants_path) %> nav-item">
          <%= link_to tenants_path, class: 'nav-link' do %>
            <div class="fas fa-user-shield <%= 'text-white' if current_page?(tenants_path) %>"></div>
            <span class="<%= 'text-white' if current_page?(tenants_path) %>">
              Tenants</span>
          <% end %>
        </li>
             <li class="<%= 'active fw-bold' if current_page?(new_tenant_path) %> nav-item">
          <%= link_to new_tenant_path, class: 'nav-link' do %>
            <div class="fas fa-user-plus <%= 'text-white' if current_page?(new_tenant_path) %>"></div>
            <span class="<%= 'text-white' if current_page?(new_tenant_path) %>">
              New tenant</span>
          <% end %>
        </li>
        <li class="<%= 'active fw-bold' if current_page?(my_tenants_path) %> nav-item">
          <%= link_to my_tenants_path, class: 'nav-link' do %>
            <div class="fas fa-file-import <%= 'text-white' if current_page?(my_tenants_path) %>"></div>
            <span class="<%= 'text-white' if current_page?(my_tenants_path) %>">
              My tenants</span>
          <% end %>
        </li>
        <li class="<%= 'active fw-bold' if current_page?(members_path) %> nav-item">
          <%= link_to members_path, class: 'nav-link' do %>
            <div class="fas fa-user-friends <%= 'text-white' if current_page?(members_path) %>"></div>
            <span class="<%= 'text-white' if current_page?(members_path) %>">
              Members</span>
          <% end %>
        </li>
        
          </ul>
          <ul class="navbar-nav mr-right">
            <li class="nav-item dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
                <b>
                  <%= current_user.email %>
                </b>
              </a>
              <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
                <%= link_to edit_user_registration_path, class: "dropdown-item #{'active' if current_page?(edit_user_registration_path)}" do %>
                  <div class="fa fa-cog"></div>
                  <b>Account settings</b>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <div class="fa fa-sign-out-alt"></div>
                  <b>Sign out</b>
                <% end %>
              </div>
            </li>
          </ul>
        
      <% else %>
        <ul class="navbar-nav mr-auto"></ul>
        <ul class="navbar-nav mr-right">
          <li class="<%= 'active font-weight-bold' if current_page?(new_user_registration_path) %> nav-item">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="<%= 'active font-weight-bold' if current_page?(new_user_session_path) %> nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="manifest" href="/manifest.json">
    
    <title>SaasTucu</title>
  
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "rails-ujs" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>


    <%= render "layouts/header" %>

    <%= render "layouts/flash_messages", :locals => {:flash => flash} %>
    
    

    <div class="container">
      <%= yield %>
    </div>
    
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> 
    
  </body>
</html>

app/views/members/_form.html.erb
<%= simple_form_for(@member) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :tenant %>
  </div>

  <div class="form-actions mt-3 mb-4">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<br>

<%= link_to new_member_path, class: 'nav-link text-black' do %>
            <div class="fas fa-plus-circle text-success"></div>
              New Member</span>
          <% end %>


<br>
<hr>

<%=  form_tag invite_members_path, method: :get do %>
  <%= email_field_tag "email", '', class: 'border border-muted ps-1', :placeholder => 'email@example.com' %>
  <%= submit_tag "Invite tenant", class: 'btn btn-light border border-info' ,data: { confirm: "Send email?" } %>
  <% %>
  <% %>
  <% %>
<% end %>
  


<hr>
<br>

<h3>
  <div class="text-center">
    <%= controller_name.humanize + ":" %>
    <%= action_name.humanize %>
    <div class="badge badge-info">
    </div>
  </div>
</h3>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>user id</th>
      <th>email</th>
      <th>tenants</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
         <td>
          <%= link_to member.user.id, member.user %>
        </td>
        <td>
          <%= member.user %>
        </td>
        <td>
          <%= link_to member.tenant.id, member.tenant %>
        </td>
        <td>
          <%= member.tenant %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @member.user_id %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @member.tenant_id %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/tenants/_form.html.erb
<%= simple_form_for(@tenant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tenants</h1>

<br>


<h3>
  <div class="text-center">
    <%= controller_name.humanize + ":" %>
    <%= action_name.humanize %>
    <div class="badge badge-info">
    </div>
  </div>
</h3>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>users</th>
    </tr>
  </thead>
  <tbody>
    <% @tenants.each do |tenant| %>
      <tr>
        <td>
          <%= link_to tenant.id, tenant %>
        </td>
        <td>
          <%= tenant.name %>
        </td>
        <td>
          <%= tenant.users.compact.join(', ') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/tenants/new.html.erb
<h1>New Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tenant.name %>
</p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>

app/views/users/index.html.erb
<h3>
  <div class="text-center">
    <%= controller_name.humanize + ":" %>
    <%= action_name.humanize %>
    <div class="badge badge-info">
    </div>
  </div>
</h3>

<br>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>email</th>
      <th>tenants</th>
      <th>Invited by email</th>
      <th>accepted invite</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user.id, user %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.tenants.compact.join(', ') %>
        </td>
         <td>
           <% if user.created_by_invite? %>
           <span class="badge bg-primary">
              <%= user.invitation_sent_at.strftime("%b %d, %Y %H:%M") %>
              by
              <%= user.invited_by.present? ?  user.invited_by  : "Anon." %>
              </span>
            <% else  %>
            <span class="badge bg-info">
              <%= "No"  %>
              </span>
            <% end  %>
        </td>
         <td>
           <% if user.invitation_accepted_at.present? %>
           <span class="badge bg-success">
              <%= user.invitation_accepted_at.strftime("%b %d, %Y %H:%M") %>
              </span>
            <% elsif user.invitation_sent_at.present?  %>
              <%= link_to 'Resend', resend_invite_user_path(user), method: :patch, class: "badge bg-info resend" %>
            <% end  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/users/show.html.erb
<b>id:</b>
<%= @user.id %>
<div class="row"></div>
<b>email:</b>
<%= @user.email %>